# _config.yml
nombre: "Leonardo Siangas Revollo"
telefono: "+591 79968653"
linkedin: "https://www.linkedin.com/in/leonardo-siangas-revollo/"
github: "https://github.com/wlsr"
correo: lsrev311@gmail.com